/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/acornfox/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["loginAcornFoxAdministrator"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/acornfox/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["logoutAcornFoxAdministrator"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/acornfox/auth/session": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getAcornFoxAdministratorSession"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/acornfox/auth/password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["rotateAcornFoxAdministratorPassword"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/acornfox/apps": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listAcornFoxApps"];
        put?: never;
        post: operations["createAcornFoxApp"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/acornfox/apps/{applicationId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                applicationId: components["parameters"]["ApplicationId"];
            };
            cookie?: never;
        };
        get: operations["getAcornFoxApp"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/acornfox/apps/{applicationId}/sources/{sourceRevisionId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                applicationId: components["parameters"]["ApplicationId"];
                sourceRevisionId: components["parameters"]["SourceRevisionId"];
            };
            cookie?: never;
        };
        get: operations["getAcornFoxSourceRevision"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/acornfox/apps/{applicationId}/deliveries": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                applicationId: components["parameters"]["ApplicationId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["createAcornFoxDelivery"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/acornfox/apps/{applicationId}/deliveries/{deploymentId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                applicationId: components["parameters"]["ApplicationId"];
                deploymentId: components["parameters"]["DeploymentId"];
            };
            cookie?: never;
        };
        get: operations["getAcornFoxDeliveryStatus"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/acornfox/apps/{applicationId}/deliveries/{deploymentId}/restart": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                applicationId: components["parameters"]["ApplicationId"];
                deploymentId: components["parameters"]["DeploymentId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["restartAcornFoxDelivery"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/acornfox/apps/{applicationId}/deliveries/{deploymentId}/redeploy": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                applicationId: components["parameters"]["ApplicationId"];
                deploymentId: components["parameters"]["DeploymentId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["redeployAcornFoxDelivery"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/acornfox/apps/{applicationId}/deliveries/{deploymentId}/logs": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                applicationId: components["parameters"]["ApplicationId"];
                deploymentId: components["parameters"]["DeploymentId"];
            };
            cookie?: never;
        };
        get: operations["listAcornFoxDeliveryLogs"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/acornfox/apps/{applicationId}/deliveries/{deploymentId}/public-access": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                applicationId: components["parameters"]["ApplicationId"];
                deploymentId: components["parameters"]["DeploymentId"];
            };
            cookie?: never;
        };
        get: operations["getAcornFoxDeliveryPublicAccess"];
        put: operations["setAcornFoxDeliveryPublicAccess"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/acornfox/apps/{applicationId}/deliveries/{deploymentId}/probes": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                applicationId: components["parameters"]["ApplicationId"];
                deploymentId: components["parameters"]["DeploymentId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["probeAcornFoxDeliveryOnce"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Error: {
            code: string;
            message: string;
        };
        AuthLoginRequest: {
            password: string;
        };
        AuthPasswordRequest: {
            current_password: string;
            new_password: string;
        };
        AuthSessionResponse: {
            authenticated: boolean;
            /** Format: date-time */
            idle_expires_at: string;
            /** Format: date-time */
            absolute_expires_at: string;
        };
        Application: {
            id: string;
            name: string;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
        };
        ApplicationListResponse: {
            items: components["schemas"]["Application"][];
        };
        CreateApplicationRequest: {
            name: string;
            source: {
                /** @enum {string} */
                type: "public_git";
                /** Format: uri */
                repository_url: string;
                ref: string;
            };
        };
        CreateApplicationResponse: {
            application: components["schemas"]["Application"];
            source_revision_id: string;
            operation_id: string;
        };
        SourceRevision: {
            id: string;
            application_id: string;
            kind: string;
            locator_sha256: string;
            ref?: string;
            commit?: string;
            content_digest: string;
            /** Format: date-time */
            created_at: string;
            immutable: boolean;
        };
        CreateDeliveryRequest: {
            source_revision_id: string;
            container_port?: number;
        };
        EmptyRequest: Record<string, never>;
        DeliveryCommandResponse: {
            deployment_id: string;
            operation_id: string;
            task_id: string;
            status: string;
        };
        ImageDigest: {
            repository: string;
            digest: string;
        };
        RuntimeRequestedResources: {
            /** Format: int64 */
            cpu_millis: number;
            /** Format: int64 */
            memory_bytes: number;
            /** Format: int64 */
            pids: number;
            /** Format: int64 */
            disk_reservation_bytes: number;
        };
        RuntimeReleaseFact: {
            application_id: string;
            environment_id: string;
            release_id: string;
            service_name: string;
            image: components["schemas"]["ImageDigest"];
            resources: components["schemas"]["RuntimeRequestedResources"];
            container_port?: number;
            /** Format: date-time */
            accepted_at: string;
            immutable: boolean;
        };
        RuntimeAppliedLimits: {
            /** Format: int64 */
            cpu_millis: number;
            /** Format: int64 */
            memory_bytes: number;
            /** Format: int64 */
            pids: number;
        };
        RuntimeDiskFact: {
            /** Format: int64 */
            reservation_bytes: number;
            accounting_reconciled: boolean;
            per_container_enforced: boolean;
        };
        RuntimeObservation: {
            deployment_id: string;
            service_name: string;
            container_id?: string;
            runtime_state: string;
            /** Format: int64 */
            restart_count: number;
            internal_address?: string;
            requested_resources: components["schemas"]["RuntimeRequestedResources"];
            applied_limits: components["schemas"]["RuntimeAppliedLimits"];
            disk: components["schemas"]["RuntimeDiskFact"];
            /** Format: date-time */
            observed_at: string;
        };
        DeliveryStatusResponse: {
            deployment: components["schemas"]["DeploymentRuntimeState"];
            desired: components["schemas"]["RuntimeReleaseFact"] | null;
            runtime: components["schemas"]["RuntimeObservation"] | null;
            response: components["schemas"]["ProbeResponseFact"] | null;
        };
        DeploymentRuntimeState: {
            id: string;
            application_id: string;
            environment_id: string;
            release_id: string;
            /** @enum {string} */
            stage: "starting" | "runtime_observed" | "failed" | "unknown";
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
        };
        ProbeDeliveryRequest: {
            /** @enum {string} */
            protocol: "tcp" | "http";
            path?: string;
        };
        ProbeResponseFact: {
            /** @enum {string} */
            protocol: "tcp" | "http";
            outcome: string;
            http_status?: number | null;
            /** Format: int64 */
            latency_ms?: number;
            error_code?: string;
            /** Format: date-time */
            observed_at: string;
            fact_digest: string;
        };
        DeliveryLogItem: {
            /** @enum {string} */
            stream: "stdout" | "stderr" | "combined" | "unknown";
            /** Format: date-time */
            recorded_at: string;
            /** @description Redacted log text; returned as the newest suffix when response limits apply. */
            content: string;
            /** @enum {string} */
            truncation: "complete" | "source_limited" | "response_limited" | "unknown";
        };
        DeliveryLogsResponse: {
            /** @enum {string} */
            source: "build" | "runtime";
            /** @enum {string} */
            availability: "available" | "not_collected" | "retired";
            items: components["schemas"]["DeliveryLogItem"][];
            next_cursor: string | null;
            /** @description True when source-specific older log indexes were retired; active items, if present, remain readable. */
            retention_limited: boolean;
        };
        PublicAccessRequest: {
            enabled: boolean;
        };
        PublicAccessResponse: {
            desired_public: boolean;
            /**
             * Format: uri
             * @description Derived HTTPS URL only; not a DNS TLS or Internet readiness claim.
             */
            url: string;
            endpoint: {
                deployment_id: string;
            };
            components: {
                /** @enum {string} */
                internal_endpoint: "accepted" | "not_observed";
                /** @enum {string} */
                local_route: "desired" | "reconcile_required" | "configured" | "disabled";
                /** @enum {string} */
                dns: "not_validated";
                /** @enum {string} */
                tls: "not_validated";
                /** @enum {string} */
                external: "not_validated";
            };
            /** @enum {string} */
            status: "PUBLIC_DISABLED" | "PENDING_EXTERNAL_VALIDATION";
        };
    };
    responses: {
        /** @description Request JSON content type or body shape is invalid */
        InvalidRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Authentication origin CSRF or session validation failed */
        AuthenticationFailed: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Authentication persistence is temporarily unavailable */
        AuthenticationUnavailable: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Resource or exact route was not found */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Idempotency key conflicts with prior input or accepted work */
        IdempotencyConflict: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Request is syntactically valid but violates an AcornFox boundary */
        ValidationFailed: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Capability dependency or persisted readback is temporarily unavailable */
        TemporarilyUnavailable: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Log source limit or opaque cursor is invalid */
        InvalidLogQuery: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Collected log storage or its integrity reconciliation is temporarily unavailable */
        LogsUnavailable: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description A local endpoint route ownership or idempotency conflict prevented the requested public-access intent */
        PublicAccessConflict: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description The optional local public-access capability is unavailable or has no configured authorized root and route provider */
        PublicAccessUnavailable: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
    };
    parameters: {
        ApplicationId: string;
        SourceRevisionId: string;
        DeploymentId: string;
        IdempotencyKey: string;
        LogSource: "build" | "runtime";
        LogLimit: number;
        /** @description Opaque base64url cursor bound to this application deployment and source. */
        LogCursor: string;
        /** @description Must equal the non-HttpOnly __Host-acornfox_csrf cookie and use the allowed Origin. */
        CSRFToken: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    loginAcornFoxAdministrator: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AuthLoginRequest"];
            };
        };
        responses: {
            /** @description Administrator session created */
            200: {
                headers: {
                    "Set-Cookie"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthSessionResponse"];
                };
            };
            400: components["responses"]["InvalidRequest"];
            401: components["responses"]["AuthenticationFailed"];
            429: components["responses"]["AuthenticationFailed"];
            503: components["responses"]["AuthenticationUnavailable"];
        };
    };
    logoutAcornFoxAdministrator: {
        parameters: {
            query?: never;
            header: {
                /** @description Must equal the non-HttpOnly __Host-acornfox_csrf cookie and use the allowed Origin. */
                "X-AcornFox-CSRF": components["parameters"]["CSRFToken"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Administrator session and CSRF cookies cleared. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["AuthenticationFailed"];
            503: components["responses"]["AuthenticationUnavailable"];
        };
    };
    getAcornFoxAdministratorSession: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Current administrator session */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthSessionResponse"];
                };
            };
            401: components["responses"]["AuthenticationFailed"];
            503: components["responses"]["AuthenticationUnavailable"];
        };
    };
    rotateAcornFoxAdministratorPassword: {
        parameters: {
            query?: never;
            header: {
                /** @description Must equal the non-HttpOnly __Host-acornfox_csrf cookie and use the allowed Origin. */
                "X-AcornFox-CSRF": components["parameters"]["CSRFToken"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AuthPasswordRequest"];
            };
        };
        responses: {
            /** @description Password changed; current session and CSRF cookies cleared. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["InvalidRequest"];
            401: components["responses"]["AuthenticationFailed"];
            503: components["responses"]["AuthenticationUnavailable"];
        };
    };
    listAcornFoxApps: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Application list */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApplicationListResponse"];
                };
            };
            401: components["responses"]["AuthenticationFailed"];
            503: components["responses"]["TemporarilyUnavailable"];
        };
    };
    createAcornFoxApp: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
                /** @description Must equal the non-HttpOnly __Host-acornfox_csrf cookie and use the allowed Origin. */
                "X-AcornFox-CSRF": components["parameters"]["CSRFToken"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateApplicationRequest"];
            };
        };
        responses: {
            /** @description Application and immutable public-Git source accepted */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreateApplicationResponse"];
                };
            };
            400: components["responses"]["InvalidRequest"];
            401: components["responses"]["AuthenticationFailed"];
            409: components["responses"]["IdempotencyConflict"];
            422: components["responses"]["ValidationFailed"];
            503: components["responses"]["TemporarilyUnavailable"];
        };
    };
    getAcornFoxApp: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                applicationId: components["parameters"]["ApplicationId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Application */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Application"];
                };
            };
            401: components["responses"]["AuthenticationFailed"];
            404: components["responses"]["NotFound"];
            503: components["responses"]["TemporarilyUnavailable"];
        };
    };
    getAcornFoxSourceRevision: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                applicationId: components["parameters"]["ApplicationId"];
                sourceRevisionId: components["parameters"]["SourceRevisionId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Redacted immutable input revision */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SourceRevision"];
                };
            };
            401: components["responses"]["AuthenticationFailed"];
            404: components["responses"]["NotFound"];
            503: components["responses"]["TemporarilyUnavailable"];
        };
    };
    createAcornFoxDelivery: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
                /** @description Must equal the non-HttpOnly __Host-acornfox_csrf cookie and use the allowed Origin. */
                "X-AcornFox-CSRF": components["parameters"]["CSRFToken"];
            };
            path: {
                applicationId: components["parameters"]["ApplicationId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateDeliveryRequest"];
            };
        };
        responses: {
            /** @description Delivery work accepted; later facts determine outcome */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeliveryCommandResponse"];
                };
            };
            400: components["responses"]["InvalidRequest"];
            401: components["responses"]["AuthenticationFailed"];
            409: components["responses"]["IdempotencyConflict"];
            422: components["responses"]["ValidationFailed"];
            503: components["responses"]["TemporarilyUnavailable"];
        };
    };
    getAcornFoxDeliveryStatus: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                applicationId: components["parameters"]["ApplicationId"];
                deploymentId: components["parameters"]["DeploymentId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Desired runtime and response facts; null means no fact was persisted */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeliveryStatusResponse"];
                };
            };
            401: components["responses"]["AuthenticationFailed"];
            404: components["responses"]["NotFound"];
            503: components["responses"]["TemporarilyUnavailable"];
        };
    };
    restartAcornFoxDelivery: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
                /** @description Must equal the non-HttpOnly __Host-acornfox_csrf cookie and use the allowed Origin. */
                "X-AcornFox-CSRF": components["parameters"]["CSRFToken"];
            };
            path: {
                applicationId: components["parameters"]["ApplicationId"];
                deploymentId: components["parameters"]["DeploymentId"];
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["EmptyRequest"];
            };
        };
        responses: {
            /** @description Restart work accepted */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeliveryCommandResponse"];
                };
            };
            400: components["responses"]["InvalidRequest"];
            401: components["responses"]["AuthenticationFailed"];
            409: components["responses"]["IdempotencyConflict"];
            422: components["responses"]["ValidationFailed"];
            503: components["responses"]["TemporarilyUnavailable"];
        };
    };
    redeployAcornFoxDelivery: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
                /** @description Must equal the non-HttpOnly __Host-acornfox_csrf cookie and use the allowed Origin. */
                "X-AcornFox-CSRF": components["parameters"]["CSRFToken"];
            };
            path: {
                applicationId: components["parameters"]["ApplicationId"];
                deploymentId: components["parameters"]["DeploymentId"];
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["EmptyRequest"];
            };
        };
        responses: {
            /** @description Recreate work accepted */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeliveryCommandResponse"];
                };
            };
            400: components["responses"]["InvalidRequest"];
            401: components["responses"]["AuthenticationFailed"];
            409: components["responses"]["IdempotencyConflict"];
            422: components["responses"]["ValidationFailed"];
            503: components["responses"]["TemporarilyUnavailable"];
        };
    };
    listAcornFoxDeliveryLogs: {
        parameters: {
            query: {
                source: components["parameters"]["LogSource"];
                limit?: components["parameters"]["LogLimit"];
                /** @description Opaque base64url cursor bound to this application deployment and source. */
                cursor?: components["parameters"]["LogCursor"];
            };
            header?: never;
            path: {
                applicationId: components["parameters"]["ApplicationId"];
                deploymentId: components["parameters"]["DeploymentId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Already-collected build or runtime records. This read does not start collection or make runtime calls. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeliveryLogsResponse"];
                };
            };
            401: components["responses"]["AuthenticationFailed"];
            404: components["responses"]["NotFound"];
            422: components["responses"]["InvalidLogQuery"];
            503: components["responses"]["LogsUnavailable"];
        };
    };
    getAcornFoxDeliveryPublicAccess: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                applicationId: components["parameters"]["ApplicationId"];
                deploymentId: components["parameters"]["DeploymentId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Local public-access intent only. This state does not claim DNS TLS or Internet reachability. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PublicAccessResponse"];
                };
            };
            401: components["responses"]["AuthenticationFailed"];
            404: components["responses"]["NotFound"];
            503: components["responses"]["PublicAccessUnavailable"];
        };
    };
    setAcornFoxDeliveryPublicAccess: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
                /** @description Must equal the non-HttpOnly __Host-acornfox_csrf cookie and use the allowed Origin. */
                "X-AcornFox-CSRF": components["parameters"]["CSRFToken"];
            };
            path: {
                applicationId: components["parameters"]["ApplicationId"];
                deploymentId: components["parameters"]["DeploymentId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PublicAccessRequest"];
            };
        };
        responses: {
            /** @description Local route intent updated. An enabled result remains pending external validation. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PublicAccessResponse"];
                };
            };
            400: components["responses"]["InvalidRequest"];
            401: components["responses"]["AuthenticationFailed"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["PublicAccessConflict"];
            422: components["responses"]["ValidationFailed"];
            503: components["responses"]["PublicAccessUnavailable"];
        };
    };
    probeAcornFoxDeliveryOnce: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
                /** @description Must equal the non-HttpOnly __Host-acornfox_csrf cookie and use the allowed Origin. */
                "X-AcornFox-CSRF": components["parameters"]["CSRFToken"];
            };
            path: {
                applicationId: components["parameters"]["ApplicationId"];
                deploymentId: components["parameters"]["DeploymentId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProbeDeliveryRequest"];
            };
        };
        responses: {
            /** @description One caller-requested loopback response probe accepted */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeliveryCommandResponse"];
                };
            };
            400: components["responses"]["InvalidRequest"];
            401: components["responses"]["AuthenticationFailed"];
            409: components["responses"]["IdempotencyConflict"];
            422: components["responses"]["ValidationFailed"];
            503: components["responses"]["TemporarilyUnavailable"];
        };
    };
}
