/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/acornfox/setup": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getAcornFoxSetupState"];
        put?: never;
        post: operations["initializeAcornFoxAdministrator"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/acornfox/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["loginAcornFoxAdministrator"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/acornfox/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["logoutAcornFoxAdministrator"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/acornfox/auth/session": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getAcornFoxAdministratorSession"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/acornfox/auth/password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["rotateAcornFoxAdministratorPassword"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/acornfox/host/metrics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getAcornFoxHostMetrics"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/acornfox/assistant/sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listAcornFoxAssistantSessions"];
        put?: never;
        post: operations["createAcornFoxAssistantSession"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/acornfox/assistant/sessions/{sessionId}/runs": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sessionId: components["parameters"]["AssistantSessionId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["submitAcornFoxAssistantRun"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/acornfox/assistant/sessions/{sessionId}/events": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sessionId: components["parameters"]["AssistantSessionId"];
            };
            cookie?: never;
        };
        get: operations["getAcornFoxAssistantEvents"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/acornfox/assistant/sessions/{sessionId}/abort": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sessionId: components["parameters"]["AssistantSessionId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["abortAcornFoxAssistantSessionRuns"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/acornfox/assistant/sessions/{sessionId}/actions": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sessionId: components["parameters"]["AssistantSessionId"];
            };
            cookie?: never;
        };
        get: operations["listAcornFoxAssistantActions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/acornfox/assistant/sessions/{sessionId}/actions/{proposalId}/decision": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sessionId: components["parameters"]["AssistantSessionId"];
                proposalId: components["parameters"]["AssistantProposalId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["decideAcornFoxAssistantAction"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/acornfox/source-uploads": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["createAcornFoxSourceUpload"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/acornfox/source-uploads/{uploadId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                uploadId: string;
            };
            cookie?: never;
        };
        get: operations["getAcornFoxSourceUpload"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/acornfox/apps": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listAcornFoxApps"];
        put?: never;
        post: operations["createAcornFoxApp"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/acornfox/apps/{applicationId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                applicationId: components["parameters"]["ApplicationId"];
            };
            cookie?: never;
        };
        get: operations["getAcornFoxApp"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/acornfox/apps/{applicationId}/sources": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                applicationId: components["parameters"]["ApplicationId"];
            };
            cookie?: never;
        };
        get: operations["listAcornFoxSourceRevisions"];
        put?: never;
        post: operations["updateAcornFoxSourceRevision"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/acornfox/apps/{applicationId}/operations/{operationId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                applicationId: components["parameters"]["ApplicationId"];
                operationId: components["parameters"]["OperationId"];
            };
            cookie?: never;
        };
        get: operations["getAcornFoxOperationResult"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/acornfox/apps/{applicationId}/sources/{sourceRevisionId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                applicationId: components["parameters"]["ApplicationId"];
                sourceRevisionId: components["parameters"]["SourceRevisionId"];
            };
            cookie?: never;
        };
        get: operations["getAcornFoxSourceRevision"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/acornfox/apps/{applicationId}/sources/{sourceRevisionId}/metadata": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                applicationId: components["parameters"]["ApplicationId"];
                sourceRevisionId: components["parameters"]["SourceRevisionId"];
            };
            cookie?: never;
        };
        get: operations["getAcornFoxSourceMetadata"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/acornfox/apps/{applicationId}/sources/{sourceRevisionId}/deployment-plan": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                applicationId: components["parameters"]["ApplicationId"];
                sourceRevisionId: components["parameters"]["SourceRevisionId"];
            };
            cookie?: never;
        };
        get: operations["getAcornFoxDeploymentPlan"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/acornfox/apps/{applicationId}/fix-candidates": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                applicationId: components["parameters"]["ApplicationId"];
            };
            cookie?: never;
        };
        get: operations["listAcornFoxFixCandidates"];
        put?: never;
        post: operations["createAcornFoxFixCandidate"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/acornfox/apps/{applicationId}/fix-candidates/{candidateId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                applicationId: components["parameters"]["ApplicationId"];
                candidateId: components["parameters"]["CandidateId"];
            };
            cookie?: never;
        };
        get: operations["getAcornFoxFixCandidate"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/acornfox/apps/{applicationId}/fix-candidates/{candidateId}/source-match": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                applicationId: components["parameters"]["ApplicationId"];
                candidateId: components["parameters"]["CandidateId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["matchAcornFoxFixCandidateSource"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/acornfox/apps/{applicationId}/fix-candidates/{candidateId}/publish": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                applicationId: components["parameters"]["ApplicationId"];
                candidateId: components["parameters"]["CandidateId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["publishAcornFoxFixCandidate"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/acornfox/apps/{applicationId}/deliveries": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                applicationId: components["parameters"]["ApplicationId"];
            };
            cookie?: never;
        };
        get: operations["listAcornFoxDeliveries"];
        put?: never;
        post: operations["createAcornFoxDelivery"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/acornfox/apps/{applicationId}/deliveries/{deploymentId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                applicationId: components["parameters"]["ApplicationId"];
                deploymentId: components["parameters"]["DeploymentId"];
            };
            cookie?: never;
        };
        get: operations["getAcornFoxDeliveryStatus"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/acornfox/apps/{applicationId}/deliveries/{deploymentId}/source": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                applicationId: components["parameters"]["ApplicationId"];
                deploymentId: components["parameters"]["DeploymentId"];
            };
            cookie?: never;
        };
        get: operations["getAcornFoxDeliverySource"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/acornfox/apps/{applicationId}/deliveries/{deploymentId}/restart": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                applicationId: components["parameters"]["ApplicationId"];
                deploymentId: components["parameters"]["DeploymentId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["restartAcornFoxDelivery"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/acornfox/apps/{applicationId}/deliveries/{deploymentId}/redeploy": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                applicationId: components["parameters"]["ApplicationId"];
                deploymentId: components["parameters"]["DeploymentId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["redeployAcornFoxDelivery"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/acornfox/apps/{applicationId}/deliveries/{deploymentId}/logs": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                applicationId: components["parameters"]["ApplicationId"];
                deploymentId: components["parameters"]["DeploymentId"];
            };
            cookie?: never;
        };
        get: operations["listAcornFoxDeliveryLogs"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/acornfox/apps/{applicationId}/deliveries/{deploymentId}/public-access": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                applicationId: components["parameters"]["ApplicationId"];
                deploymentId: components["parameters"]["DeploymentId"];
            };
            cookie?: never;
        };
        get: operations["getAcornFoxDeliveryPublicAccess"];
        put: operations["setAcornFoxDeliveryPublicAccess"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/acornfox/apps/{applicationId}/deliveries/{deploymentId}/access-observation": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                applicationId: components["parameters"]["ApplicationId"];
                deploymentId: components["parameters"]["DeploymentId"];
            };
            cookie?: never;
        };
        get: operations["getAcornFoxExternalAccessObservation"];
        put?: never;
        post: operations["reportAcornFoxExternalAccessObservation"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/acornfox/apps/{applicationId}/deliveries/{deploymentId}/probes": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                applicationId: components["parameters"]["ApplicationId"];
                deploymentId: components["parameters"]["DeploymentId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["probeAcornFoxDeliveryOnce"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Error: {
            code: string;
            message: string;
        };
        AuthLoginRequest: {
            password: string;
        };
        AuthPasswordRequest: {
            current_password: string;
            new_password: string;
        };
        SetupStateResponse: {
            /** @enum {string} */
            state: "initialized" | "uninitialized" | "unavailable";
        };
        SetupRequest: {
            setup_token: string;
            password: string;
        };
        SetupResponse: {
            /** @enum {boolean} */
            initialized: true;
        };
        AssistantScope: {
            /** @enum {string} */
            kind: "host" | "app";
            app_id?: string;
        };
        AssistantSession: {
            session_id: string;
            scope: components["schemas"]["AssistantScope"];
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
        };
        AssistantSessionListResponse: {
            sessions: components["schemas"]["AssistantSession"][];
        };
        AssistantSessionCreateRequest: {
            scope: components["schemas"]["AssistantScope"];
        };
        AssistantRun: {
            run_id: string;
            session_id: string;
            /** @enum {string} */
            status: "accepted" | "running" | "completed" | "failed" | "aborted" | "unknown";
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
        };
        AssistantRunSubmitRequest: {
            idempotency_key: string;
            message: string;
        };
        AssistantRunSubmitResponse: {
            run: components["schemas"]["AssistantRun"];
            replay: boolean;
        };
        AssistantEvent: {
            cursor: number;
            run_id?: string;
            /** @enum {string} */
            type: "run.accepted" | "run.started" | "assistant.delta" | "assistant.message" | "run.completed" | "run.failed" | "run.aborted" | "run.unknown";
            /** Format: date-time */
            occurred_at: string;
            text?: string;
        };
        AssistantEventSnapshot: {
            /** @enum {string} */
            status: "ok" | "slow_consumer" | "expired";
            oldest_cursor: number;
            latest_cursor: number;
            events: components["schemas"]["AssistantEvent"][];
        };
        AssistantAbortResponse: {
            aborted: number;
        };
        AssistantActionTarget: {
            application_id: string;
            deployment_id: string;
            target_release_id: string;
            /** Format: int64 */
            target_release_version: number;
            application_name: string;
        };
        AssistantActionVerification: {
            /** @enum {string} */
            state: "pending" | "verified" | "failed";
            verdict?: string;
            /** Format: date-time */
            observed_at?: string;
        };
        AssistantActionProposal: {
            proposal_id: string;
            session_id: string;
            run_id: string;
            /** @enum {string} */
            action: "restart" | "redeploy";
            target: components["schemas"]["AssistantActionTarget"];
            /** @enum {string} */
            state: "pending" | "rejected" | "expired" | "executing" | "accepted" | "unknown" | "verified" | "failed";
            /** Format: date-time */
            expires_at: string;
            operation_id?: string;
            verification: components["schemas"]["AssistantActionVerification"];
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
        };
        AssistantActionListResponse: {
            actions: components["schemas"]["AssistantActionProposal"][];
        };
        AssistantActionDecisionRequest: {
            approve: boolean;
        };
        AuthSessionResponse: {
            authenticated: boolean;
            /** Format: date-time */
            idle_expires_at: string;
            /** Format: date-time */
            absolute_expires_at: string;
        };
        Application: {
            id: string;
            name: string;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
        };
        ApplicationListResponse: {
            items: components["schemas"]["Application"][];
        };
        CreateApplicationRequest: {
            name: string;
            source: {
                /** @enum {string} */
                type: "public_git";
                /** Format: uri */
                repository_url: string;
                ref: string;
            } | {
                /** @enum {string} */
                type: "upload";
                upload_id: string;
            };
        };
        SourceUploadManifestEntry: {
            /** @description Normalized relative path with no empty, dot, parent or trailing-slash segment. */
            path: string;
            /** Format: int64 */
            bytes: number;
            digest: string;
        };
        SourceUploadManifest: {
            files: components["schemas"]["SourceUploadManifestEntry"][];
        };
        SourceUploadRequest: components["schemas"]["SourceUploadArchiveRequest"] | components["schemas"]["SourceUploadDirectoryRequest"];
        SourceUploadArchiveRequest: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            mode: "archive";
            /**
             * Format: binary
             * @description Required exactly once; accepted filename extensions are .zip, .tar.gz and .tgz only.
             */
            archive: string;
        };
        SourceUploadDirectoryRequest: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            mode: "directory";
            /** @description Required as repeated multipart parts. Each part filename is a normalized relative path cross-checked against manifest.files. */
            files: string[];
            manifest: components["schemas"]["SourceUploadManifest"];
        };
        SourceUploadResponse: {
            id: string;
            /** @enum {string} */
            kind: "archive" | "directory";
            /** @enum {string} */
            status: "ready" | "claimed" | "expired" | "failed";
            digest: string;
            bytes: number;
            file_count: number;
            /** Format: date-time */
            expires_at: string;
        };
        CreateApplicationResponse: {
            application: components["schemas"]["Application"];
            source_revision_id: string;
            operation_id: string;
        };
        SourceRevision: {
            id: string;
            application_id: string;
            /** @enum {string} */
            kind: "git_https" | "upload";
            locator_sha256: string;
            ref?: string;
            commit?: string;
            content_digest: string;
            /** Format: date-time */
            created_at: string;
            immutable: boolean;
        };
        SourceMetadataResponse: {
            source_revision_id: string;
            /** @enum {string} */
            availability: "available" | "unavailable";
            /** Format: uri */
            repository_url?: string;
        };
        DeploymentPlanDockerfile: {
            /** @enum {string} */
            status: "ready" | "waiting_later" | "unsupported";
            path: string;
            digest?: string;
            stage_count: number;
            final_stage?: {
                [key: string]: unknown;
            };
            workdir?: string;
            entrypoint?: {
                [key: string]: unknown;
            };
            command?: {
                [key: string]: unknown;
            };
        };
        DeploymentPlanPort: {
            port: number;
            /** @enum {string} */
            protocol: "tcp" | "udp";
            /** @enum {string} */
            source: "dockerfile_expose";
        };
        DeploymentPlanPortSelection: {
            /** @enum {string} */
            status: "selected" | "required" | "unavailable";
            reason: string;
            selected_port?: number;
            candidates: number[];
            suggested_ports?: number[];
        };
        DeploymentPlanEnvironment: {
            name: string;
            value?: string;
            redacted?: boolean;
        };
        DeploymentPlanHealthcheck: {
            present?: boolean;
            disabled?: boolean;
            /** @enum {string} */
            form?: "exec" | "shell";
            test?: string[];
            interval_seconds?: number;
            timeout_seconds?: number;
            start_period_seconds?: number;
            retries?: number;
        };
        DeploymentPlan: {
            application_id: string;
            source_revision_id: string;
            /** Format: uri */
            repository_url: string;
            ref: string;
            commit: string;
            dockerfile: components["schemas"]["DeploymentPlanDockerfile"];
            ports: components["schemas"]["DeploymentPlanPort"][];
            port_selection: components["schemas"]["DeploymentPlanPortSelection"];
            healthcheck: components["schemas"]["DeploymentPlanHealthcheck"];
            environment: components["schemas"]["DeploymentPlanEnvironment"][];
            gaps: string[];
            warnings: string[];
            required_actions: string[];
            ready_to_deploy: boolean;
        };
        SourceRevisionList: {
            items: components["schemas"]["SourceRevision"][];
            next_cursor: string | null;
        };
        SourceUpdateRequest: {
            base_source_revision_id: string;
            ref: string;
        };
        SourceUpdateResponse: {
            source_revision_id: string;
            /** @enum {string} */
            status: "imported";
        };
        FixCandidateRequest: {
            base_source_revision_id: string;
            paths: string[];
            unified_diff: string;
            container_port: number;
        };
        FixCandidateSourceMatchRequest: {
            source_revision_id: string;
        };
        FixCandidateRuntimeEvidence: {
            task_id: string;
            image: components["schemas"]["ImageDigest"];
            /** @enum {string} */
            runtime_state: "stopped";
            /** @enum {string} */
            probe_outcome: "responded";
            http_status?: number;
            /** @enum {boolean} */
            cleanup_confirmed: true;
            evidence_digest: string;
        };
        FixCandidateLifecycle: {
            candidate_id: string;
            application_id: string;
            base_source_revision_id: string;
            /** @enum {string} */
            status: "preparing" | "failed";
            /** Format: date-time */
            created_at: string;
        };
        FixCandidateValidated: {
            candidate_id: string;
            application_id: string;
            base_source_revision_id: string;
            /** Format: uri */
            base_repository_url: string;
            base_commit: string;
            base_tree_digest: string;
            patch_digest: string;
            result_tree_digest: string;
            container_port: number;
            changed_paths: string[];
            canonical_diff: string;
            validated_image: components["schemas"]["ImageDigest"];
            build_log_ref: string;
            build_evidence_digest: string;
            runtime: components["schemas"]["FixCandidateRuntimeEvidence"];
            matched_source_revision_id?: string;
            matched_commit?: string;
            /** @enum {string} */
            status: "validated" | "source_matched";
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            expires_at: string;
        };
        FixCandidate: components["schemas"]["FixCandidateLifecycle"] | components["schemas"]["FixCandidateValidated"];
        FixCandidateList: {
            items: components["schemas"]["FixCandidate"][];
        };
        OperationEvidence: {
            /** @enum {string} */
            kind: "runtime_observation" | "response_observation";
            /** @enum {string} */
            verdict: "observed" | "unhealthy";
            /** Format: date-time */
            observed_at: string;
            http_status?: number;
        };
        OperationResultResponse: {
            operation_id: string;
            operation_type: string;
            /** @enum {string} */
            status: "accepted" | "running" | "verified" | "failed" | "unknown";
            task_id?: string;
            deployment_id?: string;
            /** Format: date-time */
            accepted_at: string;
            /** Format: date-time */
            updated_at: string;
            evidence?: components["schemas"]["OperationEvidence"];
        };
        CreateDeliveryRequest: {
            source_revision_id: string;
            container_port?: number;
        };
        EmptyRequest: Record<string, never>;
        DeliveryCommandResponse: {
            deployment_id: string;
            operation_id: string;
            task_id: string;
            status: string;
        };
        ImageDigest: {
            repository: string;
            digest: string;
        };
        RuntimeRequestedResources: {
            /** Format: int64 */
            cpu_millis: number;
            /** Format: int64 */
            memory_bytes: number;
            /** Format: int64 */
            pids: number;
            /** Format: int64 */
            disk_reservation_bytes: number;
        };
        RuntimeReleaseFact: {
            application_id: string;
            environment_id: string;
            release_id: string;
            service_name: string;
            image: components["schemas"]["ImageDigest"];
            resources: components["schemas"]["RuntimeRequestedResources"];
            container_port?: number;
            /** Format: date-time */
            accepted_at: string;
            immutable: boolean;
        };
        RuntimeAppliedLimits: {
            /** Format: int64 */
            cpu_millis: number;
            /** Format: int64 */
            memory_bytes: number;
            /** Format: int64 */
            pids: number;
        };
        RuntimeDiskFact: {
            /** Format: int64 */
            reservation_bytes: number;
            accounting_reconciled: boolean;
            per_container_enforced: boolean;
        };
        RuntimeObservation: {
            deployment_id: string;
            service_name: string;
            container_id?: string;
            runtime_state: string;
            /** Format: int64 */
            restart_count: number;
            internal_address?: string;
            requested_resources: components["schemas"]["RuntimeRequestedResources"];
            applied_limits: components["schemas"]["RuntimeAppliedLimits"];
            disk: components["schemas"]["RuntimeDiskFact"];
            /** Format: date-time */
            observed_at: string;
        };
        DeliveryStatusResponse: {
            deployment: components["schemas"]["DeploymentRuntimeState"];
            desired: components["schemas"]["RuntimeReleaseFact"] | null;
            runtime: components["schemas"]["RuntimeObservation"] | null;
            response: components["schemas"]["ProbeResponseFact"] | null;
        };
        DeploymentRuntimeState: {
            id: string;
            application_id: string;
            environment_id: string;
            release_id: string;
            /** @enum {string} */
            stage: "starting" | "runtime_observed" | "failed" | "unknown";
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
        };
        DeploymentRuntimeStateList: {
            items: components["schemas"]["DeploymentRuntimeState"][];
            next_cursor: string | null;
        };
        DeliverySourceResponse: {
            deployment_id: string;
            /** @enum {string} */
            availability: "available" | "unavailable";
            source_revision_id?: string;
            commit?: string;
            ref?: string;
            /** Format: uri */
            repository_url?: string;
        };
        HostMetricsCPU: {
            logical_cores: number;
            usage_percent?: number;
        };
        HostMetricsMemory: {
            /** Format: int64 */
            total_bytes: number;
            /** Format: int64 */
            available_bytes: number;
            /** Format: int64 */
            used_bytes: number;
        };
        HostMetricsDisk: {
            /** @enum {string} */
            mountpoint: "/";
            /** Format: int64 */
            total_bytes: number;
            /** Format: int64 */
            free_bytes: number;
            /** Format: int64 */
            used_bytes: number;
        };
        HostMetricsNetwork: {
            interface: string;
            rx_bytes_per_second?: number;
            tx_bytes_per_second?: number;
        };
        HostMetricsResponse: {
            /** @enum {integer} */
            schema_version: 1;
            /** @enum {string} */
            availability: "available" | "warming_up" | "unavailable" | "unsupported";
            /** Format: date-time */
            observed_at?: string;
            stale_after_seconds: number;
            cpu?: components["schemas"]["HostMetricsCPU"];
            memory?: components["schemas"]["HostMetricsMemory"];
            disk?: components["schemas"]["HostMetricsDisk"];
            network?: components["schemas"]["HostMetricsNetwork"];
        };
        ProbeDeliveryRequest: {
            /** @enum {string} */
            protocol: "tcp" | "http";
            path?: string;
        };
        ProbeResponseFact: {
            /** @enum {string} */
            protocol: "tcp" | "http";
            outcome: string;
            http_status?: number | null;
            /** Format: int64 */
            latency_ms?: number;
            error_code?: string;
            /** Format: date-time */
            observed_at: string;
            fact_digest: string;
        };
        DeliveryLogItem: {
            /** @enum {string} */
            stream: "stdout" | "stderr" | "combined" | "unknown";
            /** Format: date-time */
            recorded_at: string;
            /** @description Redacted log text; returned as the newest suffix when response limits apply. */
            content: string;
            /** @enum {string} */
            truncation: "complete" | "source_limited" | "response_limited" | "unknown";
        };
        DeliveryLogsResponse: {
            /** @enum {string} */
            source: "build" | "runtime";
            /** @enum {string} */
            availability: "available" | "not_collected" | "retired";
            items: components["schemas"]["DeliveryLogItem"][];
            next_cursor: string | null;
            /** @description True when source-specific older log indexes were retired; active items, if present, remain readable. */
            retention_limited: boolean;
        };
        PublicAccessRequest: {
            enabled: boolean;
        };
        PublicAccessResponse: {
            desired_public: boolean;
            /**
             * Format: uri
             * @description Derived HTTPS URL only; not a DNS TLS or Internet readiness claim.
             */
            url: string;
            endpoint: {
                deployment_id: string;
            };
            components: {
                /** @enum {string} */
                internal_endpoint: "accepted" | "not_observed";
                /** @enum {string} */
                local_route: "desired" | "reconcile_required" | "configured" | "disabled";
                /** @enum {string} */
                dns: "not_validated";
                /** @enum {string} */
                tls: "not_validated";
                /** @enum {string} */
                external: "not_validated";
            };
            /** @enum {string} */
            status: "PUBLIC_DISABLED" | "PENDING_EXTERNAL_VALIDATION";
        };
        ExternalAccessDNSObservation: {
            /** @enum {string} */
            state: "observed" | "failed";
            addresses?: string[];
            /** @enum {string} */
            failure_code?: "dns_no_answer" | "dns_timeout" | "dns_lookup_failed";
        };
        ExternalAccessTLSObservation: {
            /** @enum {string} */
            state: "observed";
            certificate_sha256: string;
        } | {
            /** @enum {string} */
            state: "failed";
            /** @enum {string} */
            failure_code: "tls_connect_failed" | "tls_name_mismatch" | "tls_certificate_invalid" | "tls_timeout";
        } | {
            /** @enum {string} */
            state: "not_attempted";
        };
        ExternalAccessHTTPSObservation: {
            /** @enum {string} */
            state: "observed";
            http_status: number;
            response_sample_sha256: string;
            response_sample_bytes: number;
            response_truncated: boolean;
        } | {
            /** @enum {string} */
            state: "failed";
            /** @enum {string} */
            failure_code: "https_timeout" | "https_transport_failed";
        } | {
            /** @enum {string} */
            state: "not_attempted";
        };
        ExternalAccessObservation: {
            /** @enum {string} */
            observer: "administrator_client";
            application_id: string;
            deployment_id: string;
            hostname: string;
            report_id: string;
            /** Format: date-time */
            observed_at: string;
            /** Format: date-time */
            received_at: string;
            /** Format: date-time */
            expires_at: string;
            dns: components["schemas"]["ExternalAccessDNSObservation"];
            tls: components["schemas"]["ExternalAccessTLSObservation"];
            https: components["schemas"]["ExternalAccessHTTPSObservation"];
        };
        ExternalAccessObservationReadResponse: {
            /** @enum {string} */
            availability: "available" | "expired" | "not_observed";
            observation?: components["schemas"]["ExternalAccessObservation"];
        };
        ExternalAccessObservationReportRequest: {
            report_id: string;
            /** Format: date-time */
            observed_at: string;
            dns: components["schemas"]["ExternalAccessDNSObservation"];
            tls: components["schemas"]["ExternalAccessTLSObservation"];
            https: components["schemas"]["ExternalAccessHTTPSObservation"];
        };
    };
    responses: {
        /** @description Request JSON content type or body shape is invalid */
        InvalidRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Authentication origin CSRF or session validation failed */
        AuthenticationFailed: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Authentication persistence is temporarily unavailable */
        AuthenticationUnavailable: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Resource or exact route was not found */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Idempotency key conflicts with prior input or accepted work */
        IdempotencyConflict: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Request is syntactically valid but violates an AcornFox boundary */
        ValidationFailed: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Capability dependency or persisted readback is temporarily unavailable */
        TemporarilyUnavailable: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Log source limit or opaque cursor is invalid */
        InvalidLogQuery: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Discovery list limit or opaque cursor is invalid */
        InvalidDiscoveryQuery: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Discovery evidence is unavailable */
        DiscoveryUnavailable: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Collected log storage or its integrity reconciliation is temporarily unavailable */
        LogsUnavailable: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description A local endpoint route ownership or idempotency conflict prevented the requested public-access intent */
        PublicAccessConflict: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description The optional local public-access capability is unavailable or has no configured authorized root and route provider */
        PublicAccessUnavailable: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
    };
    parameters: {
        ApplicationId: string;
        SourceRevisionId: string;
        CandidateId: string;
        OperationId: string;
        AssistantSessionId: string;
        AssistantProposalId: string;
        AssistantAfter: number;
        LastEventID: string;
        DeploymentId: string;
        IdempotencyKey: string;
        LogSource: "build" | "runtime";
        LogLimit: number;
        /** @description Opaque base64url cursor bound to this application deployment and source. */
        LogCursor: string;
        DiscoveryLimit: number;
        /** @description Opaque versioned cursor bound to the application and list resource. */
        DiscoveryCursor: string;
        /** @description Must equal the non-HttpOnly CSRF cookie (__Host-acornfox_csrf under public HTTPS or acornfox_local_csrf under local loopback) and use the allowed Origin. */
        CSRFToken: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getAcornFoxSetupState: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Browser setup availability only; this does not expose administrator credentials. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SetupStateResponse"];
                };
            };
            503: components["responses"]["AuthenticationUnavailable"];
        };
    };
    initializeAcornFoxAdministrator: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SetupRequest"];
            };
        };
        responses: {
            /** @description Administrator was durably initialized from a single-use operator-provisioned setup token. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SetupResponse"];
                };
            };
            400: components["responses"]["InvalidRequest"];
            409: components["responses"]["IdempotencyConflict"];
            422: components["responses"]["ValidationFailed"];
            503: components["responses"]["AuthenticationUnavailable"];
        };
    };
    loginAcornFoxAdministrator: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AuthLoginRequest"];
            };
        };
        responses: {
            /** @description Administrator session created */
            200: {
                headers: {
                    "Set-Cookie"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthSessionResponse"];
                };
            };
            400: components["responses"]["InvalidRequest"];
            401: components["responses"]["AuthenticationFailed"];
            429: components["responses"]["AuthenticationFailed"];
            503: components["responses"]["AuthenticationUnavailable"];
        };
    };
    logoutAcornFoxAdministrator: {
        parameters: {
            query?: never;
            header: {
                /** @description Must equal the non-HttpOnly CSRF cookie (__Host-acornfox_csrf under public HTTPS or acornfox_local_csrf under local loopback) and use the allowed Origin. */
                "X-AcornFox-CSRF": components["parameters"]["CSRFToken"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Administrator session and CSRF cookies cleared. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["AuthenticationFailed"];
            503: components["responses"]["AuthenticationUnavailable"];
        };
    };
    getAcornFoxAdministratorSession: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Current administrator session */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthSessionResponse"];
                };
            };
            401: components["responses"]["AuthenticationFailed"];
            503: components["responses"]["AuthenticationUnavailable"];
        };
    };
    rotateAcornFoxAdministratorPassword: {
        parameters: {
            query?: never;
            header: {
                /** @description Must equal the non-HttpOnly CSRF cookie (__Host-acornfox_csrf under public HTTPS or acornfox_local_csrf under local loopback) and use the allowed Origin. */
                "X-AcornFox-CSRF": components["parameters"]["CSRFToken"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AuthPasswordRequest"];
            };
        };
        responses: {
            /** @description Password changed; current session and CSRF cookies cleared. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["InvalidRequest"];
            401: components["responses"]["AuthenticationFailed"];
            503: components["responses"]["AuthenticationUnavailable"];
        };
    };
    getAcornFoxHostMetrics: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Read-only host telemetry snapshot. Missing optional metric groups are not zero values. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HostMetricsResponse"];
                };
            };
            401: components["responses"]["AuthenticationFailed"];
            503: components["responses"]["TemporarilyUnavailable"];
        };
    };
    listAcornFoxAssistantSessions: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Administrator-owned assistant sessions only. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AssistantSessionListResponse"];
                };
            };
            401: components["responses"]["AuthenticationFailed"];
            503: components["responses"]["TemporarilyUnavailable"];
        };
    };
    createAcornFoxAssistantSession: {
        parameters: {
            query?: never;
            header: {
                /** @description Must equal the non-HttpOnly CSRF cookie (__Host-acornfox_csrf under public HTTPS or acornfox_local_csrf under local loopback) and use the allowed Origin. */
                "X-AcornFox-CSRF": components["parameters"]["CSRFToken"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AssistantSessionCreateRequest"];
            };
        };
        responses: {
            /** @description Assistant session created. This does not start an assistant run. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AssistantSession"];
                };
            };
            400: components["responses"]["InvalidRequest"];
            401: components["responses"]["AuthenticationFailed"];
            429: components["responses"]["TemporarilyUnavailable"];
            503: components["responses"]["TemporarilyUnavailable"];
        };
    };
    submitAcornFoxAssistantRun: {
        parameters: {
            query?: never;
            header: {
                /** @description Must equal the non-HttpOnly CSRF cookie (__Host-acornfox_csrf under public HTTPS or acornfox_local_csrf under local loopback) and use the allowed Origin. */
                "X-AcornFox-CSRF": components["parameters"]["CSRFToken"];
            };
            path: {
                sessionId: components["parameters"]["AssistantSessionId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AssistantRunSubmitRequest"];
            };
        };
        responses: {
            /** @description Idempotent replay of the same accepted assistant run; no second run was submitted. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AssistantRunSubmitResponse"];
                };
            };
            /** @description Assistant run accepted. Completion is represented only by later run events and does not verify an application operation. */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AssistantRunSubmitResponse"];
                };
            };
            400: components["responses"]["InvalidRequest"];
            401: components["responses"]["AuthenticationFailed"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["IdempotencyConflict"];
            429: components["responses"]["TemporarilyUnavailable"];
            503: components["responses"]["TemporarilyUnavailable"];
        };
    };
    getAcornFoxAssistantEvents: {
        parameters: {
            query?: {
                after?: components["parameters"]["AssistantAfter"];
            };
            header?: {
                "Last-Event-ID"?: components["parameters"]["LastEventID"];
            };
            path: {
                sessionId: components["parameters"]["AssistantSessionId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description JSON event snapshot or a continuing SSE stream when Accept is text/event-stream. */
            200: {
                headers: {
                    "X-AcornFox-Assistant-Cursor-Status"?: "ok" | "slow_consumer" | "expired";
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AssistantEventSnapshot"];
                    "text/event-stream": string;
                };
            };
            400: components["responses"]["InvalidRequest"];
            401: components["responses"]["AuthenticationFailed"];
            404: components["responses"]["NotFound"];
            /** @description Cursor expired. A JSON snapshot supplies the oldest and latest retained cursor for a bounded retry. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AssistantEventSnapshot"];
                };
            };
            503: components["responses"]["TemporarilyUnavailable"];
        };
    };
    abortAcornFoxAssistantSessionRuns: {
        parameters: {
            query?: never;
            header: {
                /** @description Must equal the non-HttpOnly CSRF cookie (__Host-acornfox_csrf under public HTTPS or acornfox_local_csrf under local loopback) and use the allowed Origin. */
                "X-AcornFox-CSRF": components["parameters"]["CSRFToken"];
            };
            path: {
                sessionId: components["parameters"]["AssistantSessionId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Abort was requested for this session's active and queued runs only. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AssistantAbortResponse"];
                };
            };
            400: components["responses"]["InvalidRequest"];
            401: components["responses"]["AuthenticationFailed"];
            404: components["responses"]["NotFound"];
            503: components["responses"]["TemporarilyUnavailable"];
        };
    };
    listAcornFoxAssistantActions: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sessionId: components["parameters"]["AssistantSessionId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Administrator-owned session-scoped action proposals. verified is action evidence only and does not claim application health or public reachability. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AssistantActionListResponse"];
                };
            };
            401: components["responses"]["AuthenticationFailed"];
            404: components["responses"]["NotFound"];
            503: components["responses"]["TemporarilyUnavailable"];
        };
    };
    decideAcornFoxAssistantAction: {
        parameters: {
            query?: never;
            header: {
                /** @description Must equal the non-HttpOnly CSRF cookie (__Host-acornfox_csrf under public HTTPS or acornfox_local_csrf under local loopback) and use the allowed Origin. */
                "X-AcornFox-CSRF": components["parameters"]["CSRFToken"];
            };
            path: {
                sessionId: components["parameters"]["AssistantSessionId"];
                proposalId: components["parameters"]["AssistantProposalId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AssistantActionDecisionRequest"];
            };
        };
        responses: {
            /** @description Proposal was rejected or was already terminal; no new action was accepted. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AssistantActionProposal"];
                };
            };
            /** @description Proposal action was accepted, is executing, or has an unknown execution acknowledgement. Completion remains separate action evidence. */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AssistantActionProposal"];
                };
            };
            400: components["responses"]["InvalidRequest"];
            401: components["responses"]["AuthenticationFailed"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["IdempotencyConflict"];
            503: components["responses"]["TemporarilyUnavailable"];
        };
    };
    createAcornFoxSourceUpload: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
                /** @description Must equal the non-HttpOnly CSRF cookie (__Host-acornfox_csrf under public HTTPS or acornfox_local_csrf under local loopback) and use the allowed Origin. */
                "X-AcornFox-CSRF": components["parameters"]["CSRFToken"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["SourceUploadRequest"];
            };
        };
        responses: {
            /** @description Immutable upload accepted or replayed; no host path is returned */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SourceUploadResponse"];
                };
            };
            400: components["responses"]["InvalidRequest"];
            401: components["responses"]["AuthenticationFailed"];
            409: components["responses"]["IdempotencyConflict"];
            /** @description Upload exceeds configured limits */
            413: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Multipart form data is required */
            415: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            422: components["responses"]["ValidationFailed"];
            503: components["responses"]["TemporarilyUnavailable"];
        };
    };
    getAcornFoxSourceUpload: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                uploadId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Upload metadata without storage paths */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SourceUploadResponse"];
                };
            };
            401: components["responses"]["AuthenticationFailed"];
            404: components["responses"]["NotFound"];
            503: components["responses"]["TemporarilyUnavailable"];
        };
    };
    listAcornFoxApps: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Application list */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApplicationListResponse"];
                };
            };
            401: components["responses"]["AuthenticationFailed"];
            503: components["responses"]["TemporarilyUnavailable"];
        };
    };
    createAcornFoxApp: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
                /** @description Must equal the non-HttpOnly CSRF cookie (__Host-acornfox_csrf under public HTTPS or acornfox_local_csrf under local loopback) and use the allowed Origin. */
                "X-AcornFox-CSRF": components["parameters"]["CSRFToken"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateApplicationRequest"];
            };
        };
        responses: {
            /** @description Application and immutable public-Git or claimed upload source accepted */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreateApplicationResponse"];
                };
            };
            400: components["responses"]["InvalidRequest"];
            401: components["responses"]["AuthenticationFailed"];
            409: components["responses"]["IdempotencyConflict"];
            422: components["responses"]["ValidationFailed"];
            503: components["responses"]["TemporarilyUnavailable"];
        };
    };
    getAcornFoxApp: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                applicationId: components["parameters"]["ApplicationId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Application */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Application"];
                };
            };
            401: components["responses"]["AuthenticationFailed"];
            404: components["responses"]["NotFound"];
            503: components["responses"]["TemporarilyUnavailable"];
        };
    };
    listAcornFoxSourceRevisions: {
        parameters: {
            query?: {
                limit?: components["parameters"]["DiscoveryLimit"];
                /** @description Opaque versioned cursor bound to the application and list resource. */
                cursor?: components["parameters"]["DiscoveryCursor"];
            };
            header?: never;
            path: {
                applicationId: components["parameters"]["ApplicationId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Immutable public HTTPS Git or claimed upload source revisions only */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SourceRevisionList"];
                };
            };
            401: components["responses"]["AuthenticationFailed"];
            404: components["responses"]["NotFound"];
            422: components["responses"]["InvalidDiscoveryQuery"];
            503: components["responses"]["DiscoveryUnavailable"];
        };
    };
    updateAcornFoxSourceRevision: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
                /** @description Must equal the non-HttpOnly CSRF cookie (__Host-acornfox_csrf under public HTTPS or acornfox_local_csrf under local loopback) and use the allowed Origin. */
                "X-AcornFox-CSRF": components["parameters"]["CSRFToken"];
            };
            path: {
                applicationId: components["parameters"]["ApplicationId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SourceUpdateRequest"];
            };
        };
        responses: {
            /** @description A new immutable source revision was imported; no build deployment or route changed. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SourceUpdateResponse"];
                };
            };
            401: components["responses"]["AuthenticationFailed"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["IdempotencyConflict"];
            422: components["responses"]["ValidationFailed"];
            503: components["responses"]["TemporarilyUnavailable"];
        };
    };
    getAcornFoxOperationResult: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                applicationId: components["parameters"]["ApplicationId"];
                operationId: components["parameters"]["OperationId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Read-only application-scoped operation evidence. Verified means task-scoped evidence was persisted and does not claim application health or public reachability. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OperationResultResponse"];
                };
            };
            401: components["responses"]["AuthenticationFailed"];
            404: components["responses"]["NotFound"];
            503: components["responses"]["TemporarilyUnavailable"];
        };
    };
    getAcornFoxSourceRevision: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                applicationId: components["parameters"]["ApplicationId"];
                sourceRevisionId: components["parameters"]["SourceRevisionId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Redacted immutable input revision */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SourceRevision"];
                };
            };
            401: components["responses"]["AuthenticationFailed"];
            404: components["responses"]["NotFound"];
            503: components["responses"]["TemporarilyUnavailable"];
        };
    };
    getAcornFoxSourceMetadata: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                applicationId: components["parameters"]["ApplicationId"];
                sourceRevisionId: components["parameters"]["SourceRevisionId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Public-source projection only. repository_url is absent unless public source provenance was explicitly proven. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SourceMetadataResponse"];
                };
            };
            401: components["responses"]["AuthenticationFailed"];
            404: components["responses"]["NotFound"];
            503: components["responses"]["TemporarilyUnavailable"];
        };
    };
    getAcornFoxDeploymentPlan: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                applicationId: components["parameters"]["ApplicationId"];
                sourceRevisionId: components["parameters"]["SourceRevisionId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Read-only deployment plan derived from the immutable source and its root Dockerfile. It does not build, deploy, or mutate the source. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeploymentPlan"];
                };
            };
            401: components["responses"]["AuthenticationFailed"];
            404: components["responses"]["NotFound"];
            503: components["responses"]["TemporarilyUnavailable"];
        };
    };
    listAcornFoxFixCandidates: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                applicationId: components["parameters"]["ApplicationId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Latest 50 owner-scoped candidate lifecycle facts. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FixCandidateList"];
                };
            };
            400: components["responses"]["InvalidRequest"];
            401: components["responses"]["AuthenticationFailed"];
            503: components["responses"]["TemporarilyUnavailable"];
        };
    };
    createAcornFoxFixCandidate: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
                /** @description Must equal the non-HttpOnly CSRF cookie (__Host-acornfox_csrf under public HTTPS or acornfox_local_csrf under local loopback) and use the allowed Origin. */
                "X-AcornFox-CSRF": components["parameters"]["CSRFToken"];
            };
            path: {
                applicationId: components["parameters"]["ApplicationId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FixCandidateRequest"];
            };
        };
        responses: {
            /** @description Candidate work was durably accepted; poll the returned candidate identity. */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FixCandidate"];
                };
            };
            400: components["responses"]["InvalidRequest"];
            401: components["responses"]["AuthenticationFailed"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["IdempotencyConflict"];
            422: components["responses"]["ValidationFailed"];
            503: components["responses"]["TemporarilyUnavailable"];
        };
    };
    getAcornFoxFixCandidate: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                applicationId: components["parameters"]["ApplicationId"];
                candidateId: components["parameters"]["CandidateId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Owner-scoped canonical diff and isolated validation evidence. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FixCandidate"];
                };
            };
            401: components["responses"]["AuthenticationFailed"];
            404: components["responses"]["NotFound"];
            503: components["responses"]["TemporarilyUnavailable"];
        };
    };
    matchAcornFoxFixCandidateSource: {
        parameters: {
            query?: never;
            header: {
                /** @description Must equal the non-HttpOnly CSRF cookie (__Host-acornfox_csrf under public HTTPS or acornfox_local_csrf under local loopback) and use the allowed Origin. */
                "X-AcornFox-CSRF": components["parameters"]["CSRFToken"];
            };
            path: {
                applicationId: components["parameters"]["ApplicationId"];
                candidateId: components["parameters"]["CandidateId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FixCandidateSourceMatchRequest"];
            };
        };
        responses: {
            /** @description W05 imported source repository and tree match the candidate. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FixCandidate"];
                };
            };
            400: components["responses"]["InvalidRequest"];
            401: components["responses"]["AuthenticationFailed"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["IdempotencyConflict"];
            503: components["responses"]["TemporarilyUnavailable"];
        };
    };
    publishAcornFoxFixCandidate: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
                /** @description Must equal the non-HttpOnly CSRF cookie (__Host-acornfox_csrf under public HTTPS or acornfox_local_csrf under local loopback) and use the allowed Origin. */
                "X-AcornFox-CSRF": components["parameters"]["CSRFToken"];
            };
            path: {
                applicationId: components["parameters"]["ApplicationId"];
                candidateId: components["parameters"]["CandidateId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Matching W05 source entered normal delivery after release-time OCI digest equality. */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeliveryCommandResponse"];
                };
            };
            400: components["responses"]["InvalidRequest"];
            401: components["responses"]["AuthenticationFailed"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["IdempotencyConflict"];
            422: components["responses"]["ValidationFailed"];
            503: components["responses"]["TemporarilyUnavailable"];
        };
    };
    listAcornFoxDeliveries: {
        parameters: {
            query?: {
                limit?: components["parameters"]["DiscoveryLimit"];
                /** @description Opaque versioned cursor bound to the application and list resource. */
                cursor?: components["parameters"]["DiscoveryCursor"];
            };
            header?: never;
            path: {
                applicationId: components["parameters"]["ApplicationId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Strict AcornFox runtime-task-backed deployments only */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeploymentRuntimeStateList"];
                };
            };
            401: components["responses"]["AuthenticationFailed"];
            404: components["responses"]["NotFound"];
            422: components["responses"]["InvalidDiscoveryQuery"];
            503: components["responses"]["DiscoveryUnavailable"];
        };
    };
    createAcornFoxDelivery: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
                /** @description Must equal the non-HttpOnly CSRF cookie (__Host-acornfox_csrf under public HTTPS or acornfox_local_csrf under local loopback) and use the allowed Origin. */
                "X-AcornFox-CSRF": components["parameters"]["CSRFToken"];
            };
            path: {
                applicationId: components["parameters"]["ApplicationId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateDeliveryRequest"];
            };
        };
        responses: {
            /** @description Delivery work accepted; later facts determine outcome */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeliveryCommandResponse"];
                };
            };
            400: components["responses"]["InvalidRequest"];
            401: components["responses"]["AuthenticationFailed"];
            409: components["responses"]["IdempotencyConflict"];
            422: components["responses"]["ValidationFailed"];
            503: components["responses"]["TemporarilyUnavailable"];
        };
    };
    getAcornFoxDeliveryStatus: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                applicationId: components["parameters"]["ApplicationId"];
                deploymentId: components["parameters"]["DeploymentId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Desired runtime and response facts; null means no fact was persisted */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeliveryStatusResponse"];
                };
            };
            401: components["responses"]["AuthenticationFailed"];
            404: components["responses"]["NotFound"];
            503: components["responses"]["TemporarilyUnavailable"];
        };
    };
    getAcornFoxDeliverySource: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                applicationId: components["parameters"]["ApplicationId"];
                deploymentId: components["parameters"]["DeploymentId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Source proven for this exact deployment release. Fields are absent when release source history is unavailable. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeliverySourceResponse"];
                };
            };
            401: components["responses"]["AuthenticationFailed"];
            404: components["responses"]["NotFound"];
            503: components["responses"]["TemporarilyUnavailable"];
        };
    };
    restartAcornFoxDelivery: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
                /** @description Must equal the non-HttpOnly CSRF cookie (__Host-acornfox_csrf under public HTTPS or acornfox_local_csrf under local loopback) and use the allowed Origin. */
                "X-AcornFox-CSRF": components["parameters"]["CSRFToken"];
            };
            path: {
                applicationId: components["parameters"]["ApplicationId"];
                deploymentId: components["parameters"]["DeploymentId"];
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["EmptyRequest"];
            };
        };
        responses: {
            /** @description Restart work accepted */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeliveryCommandResponse"];
                };
            };
            400: components["responses"]["InvalidRequest"];
            401: components["responses"]["AuthenticationFailed"];
            409: components["responses"]["IdempotencyConflict"];
            422: components["responses"]["ValidationFailed"];
            503: components["responses"]["TemporarilyUnavailable"];
        };
    };
    redeployAcornFoxDelivery: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
                /** @description Must equal the non-HttpOnly CSRF cookie (__Host-acornfox_csrf under public HTTPS or acornfox_local_csrf under local loopback) and use the allowed Origin. */
                "X-AcornFox-CSRF": components["parameters"]["CSRFToken"];
            };
            path: {
                applicationId: components["parameters"]["ApplicationId"];
                deploymentId: components["parameters"]["DeploymentId"];
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["EmptyRequest"];
            };
        };
        responses: {
            /** @description Recreate work accepted */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeliveryCommandResponse"];
                };
            };
            400: components["responses"]["InvalidRequest"];
            401: components["responses"]["AuthenticationFailed"];
            409: components["responses"]["IdempotencyConflict"];
            422: components["responses"]["ValidationFailed"];
            503: components["responses"]["TemporarilyUnavailable"];
        };
    };
    listAcornFoxDeliveryLogs: {
        parameters: {
            query: {
                source: components["parameters"]["LogSource"];
                limit?: components["parameters"]["LogLimit"];
                /** @description Opaque base64url cursor bound to this application deployment and source. */
                cursor?: components["parameters"]["LogCursor"];
            };
            header?: never;
            path: {
                applicationId: components["parameters"]["ApplicationId"];
                deploymentId: components["parameters"]["DeploymentId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Already-collected build or runtime records. This read does not start collection or make runtime calls. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeliveryLogsResponse"];
                };
            };
            401: components["responses"]["AuthenticationFailed"];
            404: components["responses"]["NotFound"];
            422: components["responses"]["InvalidLogQuery"];
            503: components["responses"]["LogsUnavailable"];
        };
    };
    getAcornFoxDeliveryPublicAccess: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                applicationId: components["parameters"]["ApplicationId"];
                deploymentId: components["parameters"]["DeploymentId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Local public-access intent only. This state does not claim DNS TLS or Internet reachability. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PublicAccessResponse"];
                };
            };
            401: components["responses"]["AuthenticationFailed"];
            404: components["responses"]["NotFound"];
            503: components["responses"]["PublicAccessUnavailable"];
        };
    };
    setAcornFoxDeliveryPublicAccess: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
                /** @description Must equal the non-HttpOnly CSRF cookie (__Host-acornfox_csrf under public HTTPS or acornfox_local_csrf under local loopback) and use the allowed Origin. */
                "X-AcornFox-CSRF": components["parameters"]["CSRFToken"];
            };
            path: {
                applicationId: components["parameters"]["ApplicationId"];
                deploymentId: components["parameters"]["DeploymentId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PublicAccessRequest"];
            };
        };
        responses: {
            /** @description Local route intent updated. An enabled result remains pending external validation. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PublicAccessResponse"];
                };
            };
            400: components["responses"]["InvalidRequest"];
            401: components["responses"]["AuthenticationFailed"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["PublicAccessConflict"];
            422: components["responses"]["ValidationFailed"];
            503: components["responses"]["PublicAccessUnavailable"];
        };
    };
    getAcornFoxExternalAccessObservation: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                applicationId: components["parameters"]["ApplicationId"];
                deploymentId: components["parameters"]["DeploymentId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Latest bounded administrator-client observation. available reports only this observation; it does not prove current public reachability. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExternalAccessObservationReadResponse"];
                };
            };
            401: components["responses"]["AuthenticationFailed"];
            404: components["responses"]["NotFound"];
            503: components["responses"]["TemporarilyUnavailable"];
        };
    };
    reportAcornFoxExternalAccessObservation: {
        parameters: {
            query?: never;
            header: {
                /** @description Must equal the non-HttpOnly CSRF cookie (__Host-acornfox_csrf under public HTTPS or acornfox_local_csrf under local loopback) and use the allowed Origin. */
                "X-AcornFox-CSRF": components["parameters"]["CSRFToken"];
            };
            path: {
                applicationId: components["parameters"]["ApplicationId"];
                deploymentId: components["parameters"]["DeploymentId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ExternalAccessObservationReportRequest"];
            };
        };
        responses: {
            /** @description Exact report_id replay; no second observation was stored. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExternalAccessObservation"];
                };
            };
            /** @description New administrator-client external-access observation stored. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExternalAccessObservation"];
                };
            };
            400: components["responses"]["InvalidRequest"];
            401: components["responses"]["AuthenticationFailed"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["IdempotencyConflict"];
            422: components["responses"]["ValidationFailed"];
            503: components["responses"]["TemporarilyUnavailable"];
        };
    };
    probeAcornFoxDeliveryOnce: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
                /** @description Must equal the non-HttpOnly CSRF cookie (__Host-acornfox_csrf under public HTTPS or acornfox_local_csrf under local loopback) and use the allowed Origin. */
                "X-AcornFox-CSRF": components["parameters"]["CSRFToken"];
            };
            path: {
                applicationId: components["parameters"]["ApplicationId"];
                deploymentId: components["parameters"]["DeploymentId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProbeDeliveryRequest"];
            };
        };
        responses: {
            /** @description One caller-requested loopback response probe accepted */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeliveryCommandResponse"];
                };
            };
            400: components["responses"]["InvalidRequest"];
            401: components["responses"]["AuthenticationFailed"];
            409: components["responses"]["IdempotencyConflict"];
            422: components["responses"]["ValidationFailed"];
            503: components["responses"]["TemporarilyUnavailable"];
        };
    };
}
