package domain

import (
	"regexp"
	"strings"
	"time"
)

const (
	AuthDigestHexLength          = 64
	AdminSessionIdleTimeout      = 8 * time.Hour
	AdminSessionAbsoluteTimeout  = 24 * time.Hour
	AdminLoginFailureWindow      = 15 * time.Minute
	AdminLoginLockoutDuration    = 15 * time.Minute
	AdminLoginMaxFailureAttempts = 5
)

var (
	authDigestPattern         = regexp.MustCompile(`^[0-9a-f]{64}$`)
	passwordHashSchemePattern = regexp.MustCompile(`^[a-z0-9][a-z0-9._-]{0,55}-v[1-9][0-9]*$`)
	passwordHashPattern       = regexp.MustCompile(`^\$[A-Za-z0-9][A-Za-z0-9._=-]{0,127}\$[^\s]+$`)
)

// AuthDigest is a fixed SHA-256-shaped digest. It is intentionally not a
// token: callers must hash session, CSRF, and source values before persistence.
type AuthDigest string

func (d AuthDigest) String() string { return string(d) }

func (d AuthDigest) Validate(field string) error {
	if !authDigestPattern.MatchString(string(d)) {
		return ValidationError(field + " must be a lowercase 64-character digest")
	}
	return nil
}

// AdminCredential contains no password plaintext. PasswordHash is an encoded,
// versioned value generated by a future hashing implementation.
type AdminCredential struct {
	ID                 ID         `json:"id"`
	PasswordHashScheme string     `json:"password_hash_scheme"`
	PasswordHash       string     `json:"-"`
	CredentialVersion  int64      `json:"credential_version"`
	DisabledAt         *time.Time `json:"disabled_at,omitempty"`
	CreatedAt          time.Time  `json:"created_at"`
	UpdatedAt          time.Time  `json:"updated_at"`
}

func (c AdminCredential) Validate() error {
	if err := RequireID(c.ID, "administrator id"); err != nil {
		return err
	}
	if !passwordHashSchemePattern.MatchString(c.PasswordHashScheme) {
		return ValidationError("password hash scheme must be versioned and normalized")
	}
	if len(c.PasswordHash) > 4096 || !passwordHashPattern.MatchString(c.PasswordHash) {
		return ValidationError("password hash must be an encoded versioned hash")
	}
	if c.CredentialVersion < 1 {
		return ValidationError("credential version must be positive")
	}
	if c.CreatedAt.IsZero() || c.UpdatedAt.IsZero() || c.UpdatedAt.Before(c.CreatedAt) {
		return ValidationError("administrator credential timestamps are invalid")
	}
	if c.DisabledAt != nil && c.DisabledAt.Before(c.CreatedAt) {
		return ValidationError("administrator disabled time cannot predate creation")
	}
	return nil
}

// AdminSession binds an opaque session digest to the credential version that
// created it. A password rotation invalidates older rows without needing to
// persist or replay raw tokens.
type AdminSession struct {
	ID                ID         `json:"id"`
	AdminID           ID         `json:"admin_id"`
	SessionDigest     AuthDigest `json:"-"`
	CSRFDigest        AuthDigest `json:"-"`
	CredentialVersion int64      `json:"credential_version"`
	CreatedAt         time.Time  `json:"created_at"`
	LastSeenAt        time.Time  `json:"last_seen_at"`
	IdleExpiresAt     time.Time  `json:"idle_expires_at"`
	AbsoluteExpiresAt time.Time  `json:"absolute_expires_at"`
	RevokedAt         *time.Time `json:"revoked_at,omitempty"`
}

func (s AdminSession) Validate() error {
	if err := RequireID(s.ID, "administrator session id"); err != nil {
		return err
	}
	if err := RequireID(s.AdminID, "administrator session admin id"); err != nil {
		return err
	}
	if err := s.SessionDigest.Validate("session digest"); err != nil {
		return err
	}
	if err := s.CSRFDigest.Validate("csrf digest"); err != nil {
		return err
	}
	if s.SessionDigest == s.CSRFDigest {
		return ValidationError("session and csrf digests must differ")
	}
	if s.CredentialVersion < 1 {
		return ValidationError("session credential version must be positive")
	}
	if s.CreatedAt.IsZero() || s.LastSeenAt.Before(s.CreatedAt) || !s.AbsoluteExpiresAt.Equal(s.CreatedAt.Add(AdminSessionAbsoluteTimeout)) {
		return ValidationError("session absolute lifetime is invalid")
	}
	if s.LastSeenAt.After(s.AbsoluteExpiresAt) {
		return ValidationError("session last seen cannot exceed absolute expiry")
	}
	idleExpiry := s.LastSeenAt.Add(AdminSessionIdleTimeout)
	if idleExpiry.After(s.AbsoluteExpiresAt) {
		idleExpiry = s.AbsoluteExpiresAt
	}
	if !s.IdleExpiresAt.Equal(idleExpiry) {
		return ValidationError("session idle expiry is invalid")
	}
	if s.RevokedAt != nil && s.RevokedAt.Before(s.CreatedAt) {
		return ValidationError("session revocation cannot predate creation")
	}
	return nil
}

// AdminLoginRateLimit persists only the administrator identity and a hashed
// source discriminator. G2-02 owns the login behavior that produces records.
type AdminLoginRateLimit struct {
	AdminID         ID         `json:"admin_id"`
	SourceDigest    AuthDigest `json:"-"`
	WindowStartedAt time.Time  `json:"window_started_at"`
	WindowExpiresAt time.Time  `json:"window_expires_at"`
	FailureCount    int        `json:"failure_count"`
	LastFailureAt   time.Time  `json:"last_failure_at"`
	LockedAt        *time.Time `json:"locked_at,omitempty"`
	LockedUntil     *time.Time `json:"locked_until,omitempty"`
	UpdatedAt       time.Time  `json:"updated_at"`
}

func (r AdminLoginRateLimit) Validate() error {
	if err := RequireID(r.AdminID, "login rate limit admin id"); err != nil {
		return err
	}
	if err := r.SourceDigest.Validate("login rate limit source digest"); err != nil {
		return err
	}
	if r.WindowStartedAt.IsZero() || !r.WindowExpiresAt.Equal(r.WindowStartedAt.Add(AdminLoginFailureWindow)) {
		return ValidationError("login rate limit window must be 15 minutes")
	}
	if r.LastFailureAt.Before(r.WindowStartedAt) || r.LastFailureAt.After(r.WindowExpiresAt) || r.UpdatedAt.Before(r.WindowStartedAt) {
		return ValidationError("login rate limit timestamps are invalid")
	}
	if r.FailureCount < 1 || r.FailureCount > AdminLoginMaxFailureAttempts {
		return ValidationError("login rate limit failure count is invalid")
	}
	if r.FailureCount < AdminLoginMaxFailureAttempts {
		if r.LockedAt != nil || r.LockedUntil != nil {
			return ValidationError("login rate limit cannot lock before the fifth failure")
		}
		return nil
	}
	if r.LockedAt == nil || r.LockedUntil == nil || !r.LockedAt.Equal(r.LastFailureAt) || !r.LockedUntil.Equal(r.LockedAt.Add(AdminLoginLockoutDuration)) {
		return ValidationError("login rate limit fifth failure must lock for 15 minutes")
	}
	return nil
}

func NormalizePasswordHashScheme(value string) (string, error) {
	value = strings.ToLower(strings.TrimSpace(value))
	if !passwordHashSchemePattern.MatchString(value) {
		return "", ValidationError("password hash scheme must be versioned and normalized")
	}
	return value, nil
}
