apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: open-card-demo
  namespace: open-card-demo
  labels:
    app.kubernetes.io/name: open-card-demo
    open-card.io/component: higress
spec:
  ingressClassName: higress
  tls:
    - hosts:
        - open-card.local
      secretName: open-card-demo-tls
  rules:
    - host: open-card.local
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: open-card-demo
                port:
                  number: 80
          - path: /
            pathType: Prefix
            backend:
              service:
                name: open-card-demo
                port:
                  number: 80
