from __future__ import annotations

import unittest
from pathlib import Path


ROOT = Path(__file__).resolve().parents[2]
SCRIPTS = ROOT / "scripts/mvp"


class InstallerSecurityContractTests(unittest.TestCase):
    def test_production_activation_requires_password_origin_and_edge_domain(self) -> None:
        text = (SCRIPTS / "install-host.sh").read_text(encoding="utf-8")
        for value in ("--admin-password-file", "--auth-origin", "--edge-domain", "0:600", "OPEN_CARD_AUTH_ORIGIN", "open-card-admin bootstrap", "open-card-edge.service", "open-card-edge.Caddyfile"):
            self.assertIn(value, text)
        self.assertIn("loopback-safe Edge remains active and public routes stay absent", text)
        self.assertIn("existing production installation requires upgrade.sh", text)
        self.assertIn("--require-version 0.8.0-rc.3", text)
        self.assertIn("--stage-native-bootstrap", text)
        self.assertIn("installation-identity-migrate", text)
        self.assertIn("prepare-bootstrap --expected-manifest-sha256", text)
        self.assertIn("prepare-control", text)
        self.assertIn("bootstrap-native --expected-manifest-sha256", text)
        self.assertIn("bootstrap-verify --expected-manifest-sha256", text)
        self.assertIn("bootstrap-finalize --expected-manifest-sha256", text)
        self.assertIn("--resume-public", text)
        installer = text.index('"${installer[@]}"')
        migration = text.index("migrate_installation_identity", installer)
        self.assertLess(installer, migration)
        self.assertLess(migration, text.index("prepare-bootstrap --expected-manifest-sha256"))
        self.assertIn("Historical RC2 helpers do not implement that command", text)
        self.assertEqual(text.count("migrate_installation_identity"), 2)  # definition plus fresh call
        self.assertIn("activation_rollback", text)
        self.assertIn("activation_committed=1", text)
        self.assertLess(text.index("open-card-admin bootstrap"), text.index("systemctl reload open-card-edge.service"))
        self.assertNotIn("CREATE DATABASE opencard", text)
        self.assertNotIn('database_url="postgresql://', text)

    def test_root_backup_restore_and_purge_use_installation_id_not_clean_worker_marker(self) -> None:
        backup = (SCRIPTS / "backup-control-plane.sh").read_text(encoding="utf-8")
        restore = (SCRIPTS / "restore-control-plane.sh").read_text(encoding="utf-8")
        uninstall = (SCRIPTS / "uninstall.sh").read_text(encoding="utf-8")
        for text, action in ((backup, "BACKUP:"), (restore, "RESTORE:"), (uninstall, "OPEN-CARD-PURGE:")):
            self.assertIn("/var/lib/open-card/installation-id", text)
            self.assertIn(action, text)
            self.assertNotIn("opencard-mvp-fa8f8eab-build-worker-01", text)
        self.assertIn("restore-preflight --transaction-id", restore)
        self.assertIn("exec /usr/bin/env -i PATH=/usr/sbin:/usr/bin:/sbin:/bin LANG=C LC_ALL=C \"$helper\" restore-run", restore)
        self.assertIn("--root / refuses --database-restore-command", restore)
        self.assertIn("exec /usr/bin/env -i PATH=/usr/sbin:/usr/bin:/sbin:/bin LANG=C LC_ALL=C \"$helper\" backup-create", backup)
        self.assertIn("--root / refuses release, migration, and database dump overrides", backup)
        self.assertIn("unset OPEN_CARD_DATABASE_URL DATABASE_URL", backup)
        self.assertIn("unset OPEN_CARD_DATABASE_URL DATABASE_URL", restore)
        self.assertIn("open-card-edge.service", uninstall)
        self.assertIn("preserved $data_dir, evidence, backups, installation-id, and $edge_state", uninstall)

    def test_core_installer_stages_edge_but_does_not_activate_it_without_host_profile(self) -> None:
        text = (SCRIPTS / "install.sh").read_text(encoding="utf-8")
        self.assertIn("required current migration 0024", text)
        self.assertIn('$version production candidate is missing open-card-edge.service', text)
        self.assertIn("bin/open-card-upgrade", text)
        self.assertIn("systemd/open-card-upgrade-recover.service", text)
        self.assertIn("systemd/open-card-upgrade-safe.target", text)
        self.assertIn("systemd/open-card-upgrade-finalize.service", text)
        self.assertIn("systemd/open-card-edge.service.d/10-upgrade-marker.conf", text)
        self.assertIn("bin/open-card-healthcheck", text)
        self.assertIn("systemd/open-card-healthcheck.service", text)
        self.assertIn("systemd/open-card-healthcheck.timer", text)
        self.assertIn("--stage-upgrade-substrate", text)
        self.assertIn("--stage-native-bootstrap", text)
        self.assertIn("prepare_upgrade_substrate", text)
        for unit in ("open-card-upgrade-recover.service", "open-card-upgrade-finalize.service"):
            self.assertNotIn(f"enable {unit}", text)
            self.assertNotIn(f"start {unit}", text)
        self.assertIn("existing production installation requires upgrade.sh or --stage-upgrade-substrate", text)
        self.assertIn("$version system-root activation is not supported by native bootstrap", text)
        self.assertIn("$version system-root activation requires --stage-native-bootstrap and bootstrap-native", text)
        self.assertIn('prepare_upgrade_layout_directory "$data_dir/bootstrap-transactions" "$expected_owner" 700', text)
        self.assertIn("systemctl enable open-card-upgrade-safe.target open-card-server.service open-card-agent.service open-card-buildkit.service open-card-caddy.service open-card-edge.service", text)
        self.assertIn("durability outcome is unknown", text)
        self.assertIn("E/F boot-safe activation gate", text)
        self.assertIn('candidate_version + " production candidate must declare source and migration 0024"', text)
        self.assertIn('candidate_version + " production manifest contains test-only payload"', text)
        self.assertIn('candidate_version == "0.8.0-rc.2"', text)
        self.assertIn('candidate_version == "0.8.0-rc.3"', text)
        self.assertIn("Edge stays disabled until install-host", text)
        self.assertIn("opencard-edge", text)

    def test_root_upgrade_delegates_only_after_exact_safety_boundary(self) -> None:
        text = (SCRIPTS / "upgrade.sh").read_text(encoding="utf-8")
        self.assertIn("--confirm-installation-id UPGRADE:ID", text)
        self.assertIn("PATH=/usr/sbin:/usr/bin:/sbin:/bin", text)
        self.assertIn("verified_production_program /usr/bin/python3", text)
        self.assertIn("--root / requires --activate", text)
        self.assertIn("--root / requires --expected-manifest-sha256", text)
        self.assertIn("--root / refuses --health-command, --database-dump-command, --database-restore-command, --migration-command, and --migration-dir", text)
        self.assertIn("--root / refuses --allow-downgrade", text)
        self.assertIn("--stage-upgrade-substrate", text)
        self.assertIn("run_upgrade_helper prepare-control", text)
        self.assertIn("/usr/bin/systemctl enable --now open-card-upgrade-safe.target", text)
        self.assertIn("is-enabled --quiet open-card-upgrade-safe.target", text)
        self.assertIn("is-active --quiet open-card-upgrade-safe.target", text)
        self.assertIn("upgrade-safe target RequiredBy link is missing", text)
        self.assertIn("upgrade-safe target RequiredBy link is unsafe", text)
        self.assertIn("/proc/sys/kernel/random/uuid", text)
        self.assertIn('("0.8.0-rc.0", "0.8.0-rc.1"): "rc0-legacy"', text)
        self.assertIn('("0.8.0-rc.1", "0.8.0-rc.2"): "native"', text)
        self.assertIn('("0.8.0-rc.2", "0.8.0-rc.3"): "native"', text)
        self.assertLess(text.index("unsupported production upgrade matrix"), text.index("run_upgrade_helper prepare-control"))
        self.assertIn("os.open(root, os.O_RDONLY | os.O_DIRECTORY | os.O_NOFOLLOW)", text)
        self.assertIn('os.open(name, os.O_RDONLY | os.O_DIRECTORY | os.O_NOFOLLOW, dir_fd=root_fd)', text)
        self.assertIn('os.open("manifest.json", os.O_RDONLY | os.O_NOFOLLOW, dir_fd=directory_fd)', text)
        self.assertNotIn("production upgrade is blocked", text)
        production = text.index('if [[ "$root" = "/" ]]; then\n  (( activate ))')
        delegated_exit = text.index("  exit 0\nfi\n\n# First ask the installer")
        legacy_backup = text.index('backup_args=(--root "$root"')
        self.assertLess(production, delegated_exit)
        self.assertLess(delegated_exit, legacy_backup)

    def test_healthcheck_timer_is_staged_without_pre_dns_activation(self) -> None:
        install = (SCRIPTS / "install.sh").read_text(encoding="utf-8")
        host = (SCRIPTS / "install-host.sh").read_text(encoding="utf-8")
        for value in ("open-card-healthcheck.service", "open-card-healthcheck.timer"):
            self.assertIn(value, install)
        self.assertIn("/var/lib/open-card/healthcheck /var/lib/open-card/health-secret-materials", host)
        self.assertNotIn("enable open-card-healthcheck.timer", install)
        self.assertNotIn("start open-card-healthcheck.timer", install)
        self.assertNotIn("enable --now open-card-healthcheck.timer", host)

    def test_gate6_host_capacity_profile_is_fixed_and_not_an_install_option(self) -> None:
        host = (SCRIPTS / "install-host.sh").read_text(encoding="utf-8")
        uninstall = (SCRIPTS / "uninstall.sh").read_text(encoding="utf-8")
        capacity = (SCRIPTS / "buildkit-production-capacity.sh").read_text(encoding="utf-8")
        bundle = (ROOT / "tools/worker/production_bundle.py").read_text(encoding="utf-8")
        self.assertIn("OPEN_CARD_DEDICATED_HOST_CONFIRMATION", host)
        self.assertIn("OPEN-CARD-DEDICATED-HOST", host)
        self.assertIn('"$script_dir/host-preflight.sh" --allow-prerequisites-pending', host)
        self.assertIn('"$script_dir/host-preflight.sh" --post-prerequisites', host)
        self.assertLess(host.index('"$script_dir/host-preflight.sh" --post-prerequisites'), host.index('"${installer[@]}"'))
        self.assertIn("buildkit-production-capacity.sh", host)
        self.assertIn("capacity_rollback", host)
        self.assertIn("early_preflight_receipt=", host)
        self.assertIn("post_preflight_receipt=", host)
        self.assertIn("/var/lib/open-card/evidence/host-preflight.json", host)
        self.assertIn('value.get("mode") != "post"', host)
        self.assertLess(host.index('post_preflight_receipt=$("$script_dir/host-preflight.sh" --post-prerequisites)'), host.index('"${installer[@]}"'))
        self.assertGreater(host.index("/var/lib/open-card/evidence/host-preflight.json"), host.index('"${installer[@]}"'))
        self.assertIn("20-production-capacity.conf", capacity)
        self.assertIn("MemoryMax=2G", capacity)
        self.assertIn("CPUQuota=200%", capacity)
        self.assertNotIn("--buildkit-memory", host)
        self.assertNotIn("--buildkit-cpu", host)
        self.assertIn('if (( system_root )); then\n  "$(dirname -- "$0")/buildkit-production-capacity.sh" remove', uninstall)
        self.assertIn('"host-preflight.sh",', bundle)
        self.assertIn('"buildkit-production-capacity.sh",', bundle)


if __name__ == "__main__":
    unittest.main()
