apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: higress-gateway
  namespace: monitoring
  labels:
    app.kubernetes.io/part-of: local-cloud-poc
    app.kubernetes.io/component: gateway
    release: kube-prometheus-stack
spec:
  namespaceSelector:
    matchNames:
      - higress-system
  selector:
    matchLabels:
      app: higress-gateway
      higress: higress-system-higress-gateway
  podMetricsEndpoints:
    - port: http-envoy-prom
      path: /stats/prometheus
      interval: 30s
