apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: poc-postgres
  namespace: monitoring
  labels:
    app.kubernetes.io/part-of: local-cloud-poc
    app.kubernetes.io/component: database
    release: kube-prometheus-stack
spec:
  namespaceSelector:
    matchNames:
      - poc-data
  selector:
    matchLabels:
      cnpg.io/cluster: poc-postgres
  podMetricsEndpoints:
    - port: metrics
      path: /metrics
      interval: 30s
